services:
  api:
    build: .
    ports:
      - "8000:80"    # <-- exposa directament aquí
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fantasyChampionsBD
      MYSQL_USER: fantasy_user
      MYSQL_PASSWORD: fantikri26
      MYSQL_ROOT_PASSWORD: fantikri26
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: